using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace SplineMesh
{
    /// <summary>
    /// Example of component to show the deformation of a mesh in a changing
    /// interval in spline space.
    /// 
    /// This component is only for demo purpose and is not intended to be used as-is.
    /// </summary>
    [ExecuteInEditMode]
    [RequireComponent(typeof(Spline))]
    public class ExampleContortAlong : MonoBehaviour
    {
        private Spline spline;
        private float rate = 0;
        private MeshBender meshBender;

        [HideInInspector] public GameObject generated;

        public Mesh mesh;
        public Material material { get; set; }
        public Vector3 rotation;
        public Vector3 scale;

        public float DurationInSecond;

        public WaterShaderFx puddleFx { get; set; }
        private MovementHandler player;

        private void OnValidate()
        {
        }

        public void Initialize(Material mat, MovementHandler player)
        {
            material = mat;
            this.player = player;
            Init();
        }

        public void ActivateWaterMovement()
        {
            StartCoroutine(MoveAlongSpline());
        }

        private IEnumerator MoveAlongSpline()
        {
            rate = 0f;

            while (rate < 1f)
            {
                rate += Time.deltaTime / DurationInSecond;

                float meshLength = meshBender.Source.Length;

                float start = Mathf.Min(spline.Length * rate, spline.Length - 0.0001f);
                float end = Mathf.Min(start + meshLength, spline.Length);

                meshBender.SetInterval(spline, start, end);
                meshBender.ComputeIfNeeded();
                if (end >= spline.Length)
                {
                    if (puddleFx != null)
                    {
                        puddleFx.gameObject.SetActive(true);
                        puddleFx.ActivateFx();
                    }
                }

                yield return null;
            }


            if (generated != null)
            {
                player.SetBending(false);
                Destroy(generated);
            }

            if (puddleFx != null)
                puddleFx.PauseFx();

            yield return new WaitForSeconds(2f);

            if (puddleFx != null)
                StartCoroutine(puddleFx.DeactivateFx());
        }

        private void Contort()
        {
            if (generated != null)
            {
                meshBender.SetInterval(spline, spline.Length * rate);
                meshBender.ComputeIfNeeded();
            }
        }

        private void Init()
        {
            string generatedName = "generated by " + GetType().Name;
            var generatedTranform = transform.Find(generatedName);
            generated = generatedTranform != null
                ? generatedTranform.gameObject
                : UOUtility.Create(generatedName, gameObject,
                    typeof(MeshFilter),
                    typeof(MeshRenderer),
                    typeof(MeshBender));

            generated.GetComponent<MeshRenderer>().material = material;

            meshBender = generated.GetComponent<MeshBender>();
            spline = GetComponent<Spline>();

            meshBender.Source = SourceMesh.Build(mesh)
                .Rotate(Quaternion.Euler(rotation))
                .Scale(scale);
            meshBender.Mode = MeshBender.FillingMode.Once;
            meshBender.SetInterval(spline, 0);
        }
    }
}